### ISSUE TITLE
About the results compared with all baseline on ACC@5, ACC@10

### ISSUE THREAD

**Issue by JackKoLing** [neolifer/LLM4POI#2]
It's a meaningful job. 
I noticed that all the baseline results for Acc@1 in Table 3 are from the STHGCN paper. even though the paper mentions evaluation metrics, I would like to ask why Acc@5 or Acc@10 is not used for a recommendation system task. I would like to know how LLM performs in Acc@5 or Acc@10, thank you for your work.

**Comment by neolifer** [comment]
Hi, thank you for your interest. Currently, we don't have a good way to get a top k recommendation list from LLMs after fine-tuning. Basically, you would have to run the model 10 times if you want to get 10 items, but you will very likely get some duplicate items. That's a problem we want to solve in our future work.
