### ISSUE TITLE
ask for eval_next_poi.py

### ISSUE THREAD

**Issue by JackKoLing** [neolifer/LLM4POI#4]
A great job! 

I have finished fine-tuning and obtained the weights file in the output_dir, as I am running this process on a small data set. 
![image](https://github.com/user-attachments/assets/01c49fee-44bf-4305-9ea4-ac1490c153c3)
`trainable_params = os.path.join(output_dir, "trainable_params.bin")`
However, I encountered an issue. Despite trying to locate the "trainable_params.bin" file using the path `os.path.join(output_dir, "trainable_params.bin")`, I found that the file is missing. Consequently, I attempted to use the similar file "training_args.bin", but received the following error: `AttributeError: Can't get attribute 'TrainingArguments' on <module '__main__' from 'LLM4POI/eval_next_poi.py'>`. 

Then, I add the code `class TrainingArguments(transformers.TrainingArguments):` but also have the error: `TypeError: Expected state_dict to be dict-like, got <class '__main__.TrainingArguments'>.`

So，I am confused about how to load the trained weights and which file is the trained weights. Thank you

**Comment by neolifer** [comment]
Hi, the train weights should be 'trainable_params.bin.' Can you check the checkpoint-6000 folder? It looks like the final weights are not saved.

**Comment by JackKoLing** [comment]
> Hi, the train weights should be 'trainable_params.bin.' Can you check the checkpoint-6000 folder? It looks like the final weights are not saved.

It doesn't have the file 'trainable_params.bin.' on  the checkpoint-6000 folder. I found the same issue has been ask on [https://github.com/dvlab-research/LongLoRA/issues/123](url), which means lose something save-checkpoint-code on supervised_fine_tune_qlora.py, can you check the ipdate code again which code are lose? Thank you.

**Comment by neolifer** [comment]
Hi, 
It looks like there is no 'trainable_params.bin' on my side either. You can actually find plenty of fined-tuned models with only the adapter files on huggingface. Sorry for the mislead. 

The eval_next_poi.py works just fine. The only thing that needs to be modified is to change the model_path to your actual model path.
