### ISSUE TITLE
Problem with installing metric

### ISSUE THREAD

**Issue by rh2975** [neolifer/LLM4POI#7]
Dear Peibo Li,
Even after successful installation of the virtual env (llm4poi), I am experiencing troubles with several packages. I could resolve some of them though. However, there is a package named `metric` that was used in `utils/pipeline_util.py`. Is it some used-defined package by you? I cannot install it with `pip` on python 3.11 (that was mentioned in the creation of the environment). I have tried the same with python 3.8 and 3.9 too. I am looking forward to your hearing from you in this regard.

**Comment by neolifer** [comment]
Hi,
For that package I think you can remove the parts related to it. The code there was borrowed from STHGCN but we only use it to generate datasets. If you find the same problem with other packages and they are not actually used you may also do this.
