### ISSUE TITLE
num_traj in preprocessing/to_nextpoi_kqt.py

### ISSUE THREAD

**Issue by ryonsd** [neolifer/LLM4POI#9]
Thank you for sharing your code. I have two questions.

1. To get the length of the most recent trajectory, is shape[0] correct?

    `
    num_traj = user_trajectory_data.shape[-1]
    `

 
 
 https://github.com/neolifer/LLM4POI/blob/7fc9e56f37fcf3b7b62fdba7227e1c6a6b3b9a77/preprocessing/to_nextpoi_kqt.py#L32C1

2. Is it correct that the maximum number of check-ins is set to 200 when bringing a highly similar trajectory from train data (including all users' data), and 600 when bringing a past trajectory of the target user? If you have some experiment results in case of using only target user's data, could you share the result here?

**Comment by neolifer** [comment]
Hi,
1. Thank you for pointing out the mistake. Yes, it should be shape[0].
2. The maximum number of check-ins is for all historical data. The result of using only the target user's data is reported as the second last row in Table 3.

**Comment by ryonsd** [comment]
Thank you for your quick response!
